spring.application.name=GateWay_Service

server.port=${PORT:8080}
pdf.service.base-url=${PDF_SERVICE_BASE_URL:http://localhost:8081}
image.service.base-url=${IMAGE_SERVICE_BASE_URL:http://localhost:8082}

spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=false

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
